version: 2.1

orbs:
  ios: wordpress-mobile/ios@0.0.29
  bundle-install: toshimaru/bundle-install@0.3.1

jobs:
  test:
    executor:
      name: ios/default
      xcode-version: "10.2.1"
    steps:
      - checkout
      - bundle-install/bundle-install:
          cache_key_prefix: v1-bundler
      - run:
          name: Run Tests
          command: bundle exec rspec

workflows:
  test:
    jobs:
      - test
