version: 2.1

orbs:
  bundle-install: toshimaru/bundle-install@0.3.1

jobs:
  test:
    docker:
      - image: circleci/ruby:2.4
    steps:
      - checkout
      - bundle-install/bundle-install
      - run:
          name: Run Tests
          command: bundle exec rspec

workflows:
  test:
    jobs:
      - test
